### ISSUE TITLE
Artifacts require failing because its unable to find contracts from an external package

### ISSUE THREAD

**Issue by pkieltyka** [trufflesuite/truffle-resolver#10]
In version v4.1.3 of truffle, the example here http://truffleframework.com/docs/getting_started/packages-npm worked fine for our project. However, as of v4.1.5, we are experiencing a failure during the migration.

The external package is resolved for solc, as we are build our contracts with the external sol sources. But during migration we are experiencing the following error:

```
Error: Could not find artifacts for Arcadeum from any sources
    at Resolver.require (/Users/peter/Dev/go/src/github.com/horizon-games/arcadeum/examples/ttt/node_modules/truffle/build/cli.bundled.js:63285:9)
    at Object.require (/Users/peter/Dev/go/src/github.com/horizon-games/arcadeum/examples/ttt/node_modules/truffle/build/cli.bundled.js:75142:36)
    at ResolverIntercept.require (/Users/peter/Dev/go/src/github.com/horizon-games/arcadeum/examples/ttt/node_modules/truffle/build/cli.bundled.js:219244:32)
    at /Users/peter/Dev/go/src/github.com/horizon-games/arcadeum/examples/ttt/migrations/2_deploy_ttt.js:1:26
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at /Users/peter/Dev/go/src/github.com/horizon-games/arcadeum/examples/ttt/node_modules/truffle/build/cli.bundled.js:120716:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
error An unexpected error occurred: "Command failed.
```

for now we have downgraded to 4.1.3 to keep going with our work

**Comment by pkieltyka** [comment]
I thought this bug was in the resolver, but its actually in truffle-migrate - fix is here: https://github.com/trufflesuite/truffle-migrate/pull/25
